export const SHOW_GRADUATE_MODAL = `SHOW_GRADUATE_MODAL`;

export const HIDE_GRADUATE_MODAL = `HIDE_GRADUATE_MODAL`;

export const JUDGE_MEMORY_MODE_STATUS = `JUDGE_MEMORY_MODE_STATUS`;

export const SET_GRADUATE_FALSE = `SET_GRADUATE_FALSE`;

export const SET_ISGRADUTE = `SET_ISGRADUTE`;
